INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoBlurInFolders

NoBlurInFolders_FILES = Tweak.x
NoBlurInFolders_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
